server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallback: forward:/userServiceFallback
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallback: forward:/departmentServiceFallback

resilience4j:
  circuit breaker:
    instances:
      userServiceFallBack:
        waitDurationInOpenState: 4s # Time to wait in open state before trying again
        registerHealthIndicator: true
      departmentServiceFallBack:
        waitDurationInOpenState: 4s # Time to wait in open state before trying again
        registerHealthIndicator: true

# expose endpoint to spring boot actuator
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, resilience4j

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost